extreme/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stories/', include('tracker.urls')),
]

tracker/urls.py
from django.urls import path
from . import views

app_name = 'tracker'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:story_id>/', views.tasks, name='tasks'),
    path('<int:story_id>/devs', views.devs, name='devs'),
    path('<int:story_id>/<int:task_id>/', views.times, name='times'),
    ]

tracker/models.py
from django.db import models

# Create your models here.

class Story(models.Model):
    story_name = models.CharField(max_length=20)
    story_text = models.TextField(max_length=1000)
    estimated_time = models.DurationField(default=0)
    real_time = models.DurationField(default=0, null=True)

    def __str__(self):
        return self.story_name

class Devs(models.Model):
    story = models.ForeignKey(Story, on_delete=models.CASCADE)
    dev_name = models.CharField(max_length=20)
    estimated_time = models.DurationField(default=0)
    real_time = models.DurationField(default=0, null=True)

    def __str__(self):
        return self.dev_name

class Tasks(models.Model):
    story = models.ForeignKey(Story, on_delete=models.CASCADE)
    task_name = models.CharField(max_length=100)
    iteration = models.CharField(max_length=100)
    estimated_task_time = models.DurationField(default=0)
    real_task_time = models.DurationField(default=0, null=True)

    def __str__(self):
        return self.task_name

class Time(models.Model):
    #gal cia nereikia tu foreign key, bent prie story ir dev
    story = models.ForeignKey(Story, on_delete=models.CASCADE)
    task = models.ForeignKey(Tasks, on_delete=models.CASCADE)
    dev = models.ForeignKey(Devs, on_delete=models.CASCADE)
    duration = models.DurationField(default=0, null=True)

    def __str__(self):
        return self.duration

tracker/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import Story, Tasks, Devs
from django.db.models import Sum
from datetime import timedelta


def index(request):
    # Updating Tasks and Story DB with new elapsed timed as stories page is loaded
    all_tasks = Tasks.objects.all().values_list('id', flat=True)
    for task_id in all_tasks:
        task = Tasks.objects.get(pk=task_id)
        task.real_task_time = task.time_set.aggregate(Sum('duration'))['duration__sum']
        task.save()

    for story_id in Story.objects.all().values_list('id',flat=True):
        story = Story.objects.get(pk=story_id)
        story.real_time = story.tasks_set.aggregate(Sum('real_task_time'))['real_task_time__sum']
        story.save()

    stories_list = Story.objects.all()
    context = {'stories_list': stories_list}
    template = loader.get_template('tracker/index.html')
    return HttpResponse(template.render(context,request))


def devs(request,story_id):
    # Updating Devs DB with new elapsed timed as Developers page is loaded
    all_devs = Devs.objects.all().values_list('id', flat=True)
    for dev_id in all_devs:
        dev = Devs.objects.get(pk=dev_id)
        dev.real_time = dev.time_set.aggregate(Sum('duration'))['duration__sum']
        dev.save()

    dev_info = False
    story_name = Story.objects.get(pk=story_id).story_name

    # Checking if method is POST and adding info for response
    if request.method=="POST":
        dev_info = Devs.objects.get(pk=request.POST['developer'])

    devs_list = Story.objects.get(pk=story_id)
    context = {'devs_list':devs_list, 'story_id':story_id, 'dev_info':dev_info, 'story_name':story_name}
    return render(request, 'tracker/devs.html', context)


def tasks(request, story_id):
    tasks_list = Story.objects.get(pk=story_id)
    context={'tasks_list':tasks_list, 'story_id':story_id}
    return render(request, 'tracker/tasks.html', context)


def times(request, story_id, task_id):
    # Checking request method. If method is POST checking entered times and returning to page with
    # error message if time entered in wrong format
    if request.method == 'POST':
        hours = request.POST['hours']
        minutes = request.POST['minutes']
        try:
            hours = int(hours)
            minutes = int(minutes)
            if hours < 0 or minutes < 0 or minutes > 59:
                raise Exception
        except:
            story = Story.objects.get(pk=story_id)
            task_info = story.tasks_set.get(pk=task_id)
            context = {'task_info': task_info, 'story_id': story_id, 'task_id': task_id, 'story': story, 'error_message': "Time entered in bad format!"}
            return render(request, 'tracker/times.html', context)

    # saving entered time to databases
        dev_id = request.POST['developer']

        task = Tasks.objects.get(pk=task_id)
        task.time_set.create(duration=timedelta(hours=hours, minutes=minutes), story_id=story_id, dev_id=dev_id)
        task.real_task_time = task.time_set.aggregate(Sum('duration'))['duration__sum']
        task.save()

        story = Story.objects.get(pk=story_id)
        story.real_time = story.tasks_set.aggregate(Sum('real_task_time'))['real_task_time__sum']
        story.save()

        dev = story.devs_set.get(pk=dev_id)
        dev.real_time = story.time_set.filter(dev_id = dev_id).aggregate(Sum('duration'))['duration__sum']
        dev.save()

    story = Story.objects.get(pk=story_id)
    task_info = story.tasks_set.get(pk=task_id)
    context={'task_info':task_info, 'story_id':story_id, 'task_id':task_id, 'story':story}
    return render(request, 'tracker/times.html', context)

tracker/templates/tracker/devs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
    table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
    text-align: left;
    }
    </style>
</head>
<body>

<form action="{% url 'tracker:devs' story_id=story_id %}" method="post">
    {% csrf_token %}
    <h4>Choose a developer to get info about his working time</h4>
    <select name="developer">
        {% for dev in devs_list.devs_set.all %}
            <option value="{{dev.id}}">{{dev.dev_name}}</option>
        {% endfor %}
    </select>
    &nbsp;
    <input type="submit" value="Get Info">
</form>
<br>
<br>
{% if dev_info %}
    <table style="width:70%">
         <tr>
            <th>Developer name</th>
            <th>Story name</th>
            <th>Estimated time</th>
            <th>Elapsed time</th>
         </tr>
        <tr>
            <td>{{ dev_info.dev_name }}</td>
            <td>{{ story_name }}</td>
            <td>{{ dev_info.estimated_time }}</td>
            <td>{{ dev_info.real_time }}</td>
        </tr>
    </table>
<br>
<br>
{% else %}
{% endif %}

<form>
    <button formaction="{% url 'tracker:index' %}">Back to stories page</button>
</form>

</body>
</html>

tracker/templates/tracker/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stories</title>
    <style>
    table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
    text-align: left;
    }
    </style>
</head>
<body>
{% if stories_list %}
    <table style="width:70%">
         <tr>
            <th>Story name</th>
            <th>Story text</th>
            <th>Story tasks</th>
            <th>Developers</th>
            <th>Estimated time</th>
            <th>Elapsed time</th>
         </tr>
    {% for story in stories_list %}
        <tr>
            <td>{{ story.story_name }}</td>
            <td>{{ story.story_text }}</td>
            <td><a href="{% url 'tracker:tasks' story.id %}">{{ story.story_name }} tasks list</a></td>
            <td><a href="{% url 'tracker:devs' story.id %}">{{ story.story_name }} developers </a></td>
            <td>{{ story.estimated_time }}</td>
            <td>{{ story.real_time }}</td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>There are no stories recorded</p>
{% endif %}
</body>
</html>

tracker/templates/tracker/tasks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
    table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
    text-align: left;
}
</style>
</head>
<body>
{% if tasks_list.tasks_set.all %}
    <table style="width:70%">
      <tr>
        <th>Task name</th>
        <th>Story name</th>
        <th>Iteration</th>
        <th>Estimated task time</th>
        <th>Elapsed time for task</th>
        <th>Enter information for task</th>
      </tr>
    {% for task in tasks_list.tasks_set.all %}
      <tr>
        <td>{{ task.task_name }}</td>
        <td>{{ tasks_list.story_name }}</td>
        <td>{{ task.iteration }}</td>
        <td>{{ task.estimated_task_time }}</td>
        <td>{{ task.real_task_time }}</td>
        <td><a href="{% url 'tracker:times' story_id=story_id task_id=task.id %}">{{ task.task_name }}</a></td>
      </tr>
    {% endfor %}
    </table>
<br>
<br>
<form>
    <button formaction="{% url 'tracker:index' %}">Back to stories page</button>
</form>

{% else %}
    <p>There are no tasks recorded</p>
{% endif %}

</body>
</html>

tracker/templates/tracker/times.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>times</title>
    <style>
    table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
    text-align: left;
    }
    .SmallInput { width: 30px; height: 10px; }
    </style>
</head>

<body>
<form action="{% url 'tracker:times' story_id=story_id task_id=task_id %}" method="post">
{% csrf_token %}
    <h4>Enter information for {{ task_info.task_name }}</h4>
    Choose developer:<br>
    <select name="developer">
    {% for dev in story.devs_set.all %}
        <option value="{{dev.id}}">{{dev.dev_name}}</option>
    {% endfor %}
    </select>
    <br>
    {% if error_message %}
        <br>
        <b>{{ error_message }}</b>
    {% endif %}
    <br>
    Enter spent time for this task in format hh:mm. Number of minutes should be less than 60.
    <br>
    <!--<input type="text" name="task_duration" value="hh:mm">-->
    <input type="text" name="hours" value="HH" class="SmallInput">:
    <input type="text" name="minutes" value="mm" class="SmallInput">
    <br>
    <input type="submit" value="Submit">
</form>
<br>
<br>
 <table style="width:70%">
         <tr>
            <th>Task name</th>
            <th>Story name</th>
            <th>Iteration</th>
            <th>Estimated time</th>
            <th>Elapsed time</th>
         </tr>
        <tr>
            <td>{{ task_info.task_name }}</td>
            <td>{{ story.story_name }}</td>
            <td>{{ task_info.iteration }}</td>
            <td>{{ task_info.estimated_task_time }}</td>
            <td>{{ task_info.real_task_time }}</td>
        </tr>
    </table>
<br>
<br>
<form>
    <button formaction="{% url 'tracker:tasks' story_id=story_id %}">Back to tasks page</button>
    <button formaction="{% url 'tracker:index' %}">Back to stories page</button>
</form>
</body>
</html>


{% comment %}
<!--<form action="{% url 'tracker:register' story_id=story_number task_id=task_number %}" method="post">-->
<!--{% csrf_token %}-->
<!--{% for task in tasks_list.tasks_set.all %}-->
    <!--<input type="text" name="task" id="task{{ forloop.counter }}" value="{{ task.id }}">-->
    <!--<label for="task{{ forloop.counter }}">{{ task.task_name }}</label><br>-->
<!--{% endfor %}-->
<!--<input type="submit" value="Vote">-->
<!--</form>-->
{% endcomment %}